# syntax=docker/dockerfile:1
FROM golang:1.20

ENV APP_MAIN_ENTRY_PATH=cmd/logistics
ENV APP_BINARY_NAME=coop_logistics
ENV CLIENT_SERVICE_HOST "0.0.0.0"
ENV CLIENT_SERVICE_PORT 50051

RUN apt-get update && apt-get install -y iputils-ping telnet

WORKDIR /opt/app

COPY . .

WORKDIR /opt/app/src/client

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -a -v -o "${APP_MAIN_ENTRY_PATH}/${APP_BINARY_NAME}" "./${APP_MAIN_ENTRY_PATH}"

EXPOSE $CLIENT_SERVICE_PORT

CMD ["sh", "-c", "./${APP_MAIN_ENTRY_PATH}/${APP_BINARY_NAME}"]
