// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/coopnorge/interview-backend/src/client/internal/app/logistics"
	"github.com/coopnorge/interview-backend/src/client/internal/app/logistics/config"
	"github.com/coopnorge/interview-backend/src/client/internal/app/logistics/services/client"
	"github.com/coopnorge/interview-backend/src/client/internal/app/logistics/services/operator"
)

// Injectors from wire.go:

// newWire create new DI
func newWire(cfg *config.ClientAppConfig) (*logistics.ServiceInstance, func(), error) {
	apiLogisticsClient := client.NewLogisticsClient()
	worldOperator := operator.NewWorldOperator()
	serviceInstance, err := logistics.NewServiceInstance(apiLogisticsClient, worldOperator, cfg)
	if err != nil {
		return nil, nil, err
	}
	return serviceInstance, func() {
	}, nil
}
