// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gsasso/go-backend/src/server/internal/controller"
	"github.com/gsasso/go-backend/src/server/internal/server"
	"github.com/gsasso/go-backend/src/server/internal/ticker"
)

// Injectors from wire.go:

func Initialize() *server.LogisticServer {
	summary := ticker.Summary{}
	logisticCtlr := controller.NewLogisticController(summary)
	logisticServer := server.RunGRPCServer(logisticCtlr)
	return logisticServer
}
