// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gsasso/go-backend/src/server/internal/controller"
	"github.com/gsasso/go-backend/src/server/internal/server"
)

// Injectors from wire.go:

func InitializeApp() *server.LogisticServer {
	logisticCtlr := controller.NewLogisticController()
	logisticServer := server.RunGRPCServer(logisticCtlr)
	return logisticServer
}
